# Generated by Django 4.1.3 on 2022-11-12 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PosterArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('releaseYear', models.IntegerField(default=0)),
                ('images', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.imagelist')),
            ],
        ),
        migrations.AddField(
            model_name='imagelist',
            name='posterArt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.posterart'),
        ),
    ]
